Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/kinetic64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder "../devops/", "/var/www/website"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
